id = "arduino"
name = "Arduino"
description = "Arduino support."
version = "0.0.1"
schema_version = 1
authors = ["ChocolateNao <andrey12q112@gmail.com>"]
repository = "https://github.com/ChocolateNao/zed-arduino"

[grammars.arduino]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-arduino"
# release v0.23.0
commit = "ce02903e3ae74c729e9415dc32c276447b1c8afd"